image: 
  name: docker/compose:latest
  entrypoint: [""]

stages:
  - build
  - test

variables:
  TAG: $CI_BUILD_REF
  IMAGE: $CI_REGISTRY_IMAGE

services:
  - docker:dind

image: docker

before_script:
  - apk add --no-cache git curl build-base autoconf automake make
  - apk add --no-cache build-base linux-headers musl-dev libffi-dev openssl-dev openssh
  - apk add --no-cache rust cargo py3-pip python3-dev py-virtualenv
  - pip3 install docker-compose
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker-compose -f docker-compose.common.yml -f docker-compose.prod.yml build
    - docker-compose -f docker-compose.common.yml -f docker-compose.prod.yml push

test-python:
  stage: test
  script:
    - docker-compose -f docker-compose.common.yml -f docker-compose.prod.yml pull python
    - docker-compose -f docker-compose.common.yml -f docker-compose.prod.yml run --rm --entrypoint pytest python