version: '2'
services:
  python:
    image: bretttolbert/verbecc-svc/python:dev
    ports:
      - "8000:8000"
    command: ["uvicorn", "verbecc_svc:app", "--host", "0.0.0.0", "--reload", "--port", "8000"]
    volumes:
      - ./python/:/code
  python-tests:
    image: bretttolbert/verbecc-svc/python:dev
    volumes:
      - ./python/:/code
    entrypoint: pytest -vv -l
    depends_on:
      - python
