version: '2'
services:
  python:
    image: registry.gitlab.com/bretttolbert/verb-conjugate-fr/python:dev
    ports:
      - "8000:8000"
    command: ["uvicorn", "verb_conjugate_fr:app", "--host", "0.0.0.0", "--reload", "--port", "8000"]
    volumes:
      - ./python/:/code
  python-tests:
    image: registry.gitlab.com/bretttolbert/verb-conjugate-fr/python:dev
    volumes:
      - ./python/:/code
    entrypoint: pytest -vv
    depends_on:
      - python
